# Generated by Django 3.1.1 on 2020-09-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogalle', '0005_auto_20200918_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='photo',
        ),
        migrations.AddField(
            model_name='photo',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='galleries', to='photogalle.Gallery'),
        ),
    ]
