# Generated by Django 3.1.1 on 2020-10-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogalle', '0007_auto_20200925_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='photo',
            field=models.ManyToManyField(blank=True, related_name='galleries', to='photogalle.Photo'),
        ),
    ]
