# Generated by Django 3.1.1 on 2020-10-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogalle', '0009_auto_20201001_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='photo',
        ),
        migrations.AddField(
            model_name='gallery',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='galleries', to='photogalle.Photo'),
        ),
    ]
